import { Achievement } from '../types/achievement';

export const INITIAL_ACHIEVEMENTS: Achievement[] = [
  {
    id: 'first_victory',
    title: '첫 승리의 기쁨',
    description: '어떤 난이도든 처음으로 슬라이딩 퍼즐을 완성하세요.',
    iconName: 'Trophy',
    unlockedAt: null,
  },
  {
    id: 'speed_demon',
    title: '스피드 데몬',
    description: '3×3 퍼즐을 30초 이내에 번개처럼 클리어하세요.',
    iconName: 'Zap',
    unlockedAt: null,
  },
  {
    id: 'master_tactician',
    title: '전략의 마스터',
    description: '4×4 퍼즐을 50수 이하의 최소 이동으로 정복하세요.',
    iconName: 'Compass',
    unlockedAt: null,
  },
  {
    id: 'grandmaster_5x5',
    title: '5×5 그랜드마스터',
    description: '최고 난이도인 5×5 마스터 퍼즐을 클리어하세요.',
    iconName: 'Crown',
    unlockedAt: null,
  },
  {
    id: 'star_collector',
    title: '별들의 수집가',
    description: '만점(3성) 클리어를 누적 3회 달성하세요.',
    iconName: 'Star',
    unlockedAt: null,
    progress: 0,
    maxProgress: 3,
  },
  {
    id: 'purist_no_undo',
    title: '완벽한 직관 (No Undo)',
    description: '되돌리기(Undo)를 단 한 번도 쓰지 않고 클리어하세요.',
    iconName: 'ShieldCheck',
    unlockedAt: null,
  },
  {
    id: 'daily_streak_3',
    title: '작심삼일 탈출',
    description: '일일 챌린지를 3일 연속으로 완료하여 스트릭을 달성하세요.',
    iconName: 'Flame',
    unlockedAt: null,
    progress: 0,
    maxProgress: 3,
  },
  {
    id: 'theme_explorer',
    title: '테마 탐험가',
    description: '4종의 기본 테마(자연, 픽셀, 추상, 동물)로 모두 승리하세요.',
    iconName: 'Palette',
    unlockedAt: null,
    progress: 0,
    maxProgress: 4,
  },
  {
    id: 'custom_photographer',
    title: '세상에 단 하나뿐인 퍼즐',
    description: '내 사진을 직접 업로드하여 만든 퍼즐을 클리어하세요.',
    iconName: 'Camera',
    unlockedAt: null,
  },
  {
    id: 'time_attack_survivor',
    title: '극한의 생존자',
    description: '타임어택 하드코어 모드에서 시간 내에 퍼즐을 완성하세요.',
    iconName: 'Clock',
    unlockedAt: null,
  },
  {
    id: 'move_limit_master',
    title: '강철의 의지',
    description: '이동수 제한 하드코어 모드에서 이동수 소진 없이 승리하세요.',
    iconName: 'Footprints',
    unlockedAt: null,
  },
  {
    id: 'puzzle_legend',
    title: '슬라이딩 레전드',
    description: '위의 모든 업적을 달성하여 전설의 퍼즐러가 되세요.',
    iconName: 'Medal',
    unlockedAt: null,
    progress: 0,
    maxProgress: 11,
  },
];
